language: node_js
node_js:
  - 'stable'
  - '0.12'
env:
before_script:
  - npm install -g gulp cnpm
  - gulp -v
  - cnpm -v
script:
  - npm run lint
  - npm run build

  - rm -rf node_modules
  - cnpm install
  - rm -rf node_modules

  - cd examples
  - npm install
  - npm test
  - gulp build
  - gulp build --p

  - rm -rf node_modules
  - cnpm install
  - npm test
  - gulp build
  - gulp build --p
